name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt secrets
        run: echo ${{ secrets.ENCRYPT_KEY }} | release/signing-unpack.sh
      - name: Deploy to Sonatype
        run: |
          ./gradlew publish --no-parallel --stacktrace
          ./gradlew closeAndReleaseRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      - name: Build AAB & APK
        run: |
          ./gradlew :catalog:bundleRelease :catalog:assembleRelease
      - name: Upload APK to release
        uses: softprops/action-gh-release@v1
        id: release
        with:
          files: |
            catalog/build/outputs/apk/release/catalog-release.apk
      - name: Prepare Release Notes
        run: |
          mkdir whatsnew
          URL=https://api.github.com/repos/kiwicom/orbit-compose/releases/${{ steps.release.outputs.id }}
          curl --url $URL --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq '.body' > whatsnew/whatsnew-en-US
          sed -i 's/<table>.*<\/table>//g' whatsnew/whatsnew-en-US
      - name: Release to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: release/service-account.json
          packageName: kiwi.orbit.compose.catalog
          releaseFiles: catalog/build/outputs/bundle/release/catalog-release.aab
          track: production
          whatsNewDirectory: whatsnew
          mappingFile: catalog/build/outputs/mapping/release/mapping.txt
      - name: Clean secrets
        if: always()
        run: release/signing-cleanup.sh
