name: Release

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt secrets
        run: release/signing-unpack.sh ${{ secrets.ENCRYPT_KEY }}
      - name: Deploy to Sonatype
        run: |
          ./gradlew publish --no-parallel --stacktrace
          ./gradlew closeAndReleaseRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      - name: Build AAB & APK
        run: |
          ./gradlew :catalog:bundleRelease :catalog:assembleRelease
      - name: Upload APK to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            catalog/build/outputs/apk/release/catalog-release.apk
      - name: Store AAB output
        uses: actions/upload-artifact@v2
        with:
          name: aab-build
          path: catalog/build/outputs/bundle/release/catalog-release.aab
          retention-days: 2
      - name: Clean secrets
        if: always()
        run: release/signing-cleanup.sh
